# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.4

env:
  #matrix:
  #- DJANGO='django16'
  - DJANGO='1.6'
  - DJANGO='1.7'
  - DJANGO='1.8'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO
  - python setup.py install

script: python manage.py test

after_success: coveralls
